name: inwardsshadowcontainer
description: "Allows to add shadows to any side of a Widget"
version: 1.0.1
homepage: https://github.com/NoirsCodingCorner/InwardsShadowContainer
environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0